### ISSUE TITLE
black screen and reboot after verbose mode

### ISSUE THREAD

**Issue by RubenOliveira8** [jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H#2]
system just goes to black screen and reboot after verbose mode, tried recompiling the dgpu aml but no success.

**Comment by RubenOliveira8** [comment]
i forget to metion, i have the legion 5 17 inch ryzen 7 and rtx 3060

**Comment by jimlee2048** [comment]
Hi! To be clared first, the pre-built OpenCore from this repository is specifically target for model `Lenovo Legion R7000P2020H (82GR)`. Its compatibility with other models cannot be guaranteed due to hardware differences between generations and models, althought they might within the same product line. I can only offer some general suggestions here:

1. Are you in `macOS 14.4 Beta`? It's a known problem that iGPU Driver `NootedRed.kext` won't work on macOS 14.4, see: https://github.com/ChefKissInc/NootedRed/issues/226
2. If black screen occur during system installation or first time booting, please disable `NootedRed.kext` untill you finished all installion process and get into desktop. It's a known problem. Disable it temporarily every time you gonna install or upgrade macOS. 
3. Try reset NVRAM.
4. Maybe bad kext loading order , try to do a `OC Snapshot` to your `config.plist` using [ProperTree](https://github.com/corpnewt/ProperTree)
5. Maybe XHC0 problem, follow this guide to disable:
  > Known Problem 4: The system fails to start and gets stuck at a certain point occasionally
  >   - Temporary solution: Press and hold the power button to force shutdown, then try restarting again. If it doesn't work, try forcing restart multiple times.
  >   - Permanent solution: Disable XHC0 (ACPI->check SSDT-XCH0-DISABLE.aml) & disable modified XHCI driver (Kext->uncheck GenericUSBXHCI). Note: This solution will disable two USB ports (top C port & left A port)
6. Maybe bad ACPI patching, you can get yours following [this guide](https://chefkissinc.github.io/guide/gathering-files/acpi), and add [bumblebee-method ACPI patch](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html#bumblebee-method) to disable dGPU.

**Comment by jimlee2048** [comment]
Closing this issue due to non-targeted models. 
We can still discuss under this issue. :)
